[about]
title = "Kavasaki Launcher"
description = "A best minecraft launcher"
docsLink = "https://vk.com/kavasakila"
version = "1.4"

[file]
rpFileName = "SUHOGRUZx.zip"
nopFileName = "newMineOptions.txt"

[path]
minecraftDirPathName = "kavasaki"
curentPath = "C:\\Program Files(x86)\\kavasaki"
dataPath = "data"
backgroundPath = "\\data\\images\\bg.jpg"
iconPath = "data/images/icon.ico"